project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
    - "*.qmd"
    
website:
  title: "Prairie Tagore Society"
  image: "images/RabindranathTagore.jpg" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: upcomingevents/index.qmd
        text: Upcoming Events
      - href: pastevents/index.qmd
        text: Past Events
      - href: gallery/index.qmd
        text: Photo Gallery

format:
  html:
    fontsize: 1.0em
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

