project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
    - index.qmd
    - about.qmd
    - posts/

website:
  title: "Prairie Tagore Society"
  image: "images/RabindranathTagore.jpg" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

