project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
    - "*.qmd"
    
website:
  title: ""
  image: "images/RabindranathTagore.jpg" 
  navbar:
    background: "#000d33"
    left:
      - href: index.qmd
        text: ''
      - href: upcomingevents/index.qmd
        text: Upcoming Events
      - href: pastevents/index.qmd
        text: Past Events
      - href: gallery/index.qmd
        text: Photo Gallery
  page-footer:
    left: "Copyright 2026, Praire Tagore Society"
    right: "Contact: 5646 Campling Ave Regina, SK S4W 0L6"
    background: "#000d33"

format:
  html:
    fontsize: 1.0em
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

